services:
  app:
    container_name: strategic-programming-exercise-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - type: bind
        source: ../
        target: /workspaces/strategic-programming-exercise/
    tty: true
