# hadolint ignore=DL3007
FROM ubuntu:latest

WORKDIR /workspaces/strategic-programming-exercise/

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get --no-install-recommends -y install git gnupg2 ca-certificates gcc g++ make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists
